{% set name = "luxpy" %}
{% set version = "1.11.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 5ffdec1eea517cd59b12addb3265f39f318fbda569d6f21221a0d4c5a4cc302f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - numpy
    - pip
    - python
    - scipy
  run:
    - numpy
    - python
    - scipy

test:
  imports:
    - luxpy
    - luxpy.color
    - luxpy.color.cam
    - luxpy.color.cat
    - luxpy.color.cct
    - luxpy.color.cct.robertson1968
    - luxpy.color.cri
    - luxpy.color.cri.VFPX
    - luxpy.color.cri.iestm30
    - luxpy.color.cri.indices
    - luxpy.color.cri.utils
    - luxpy.color.ctf
    - luxpy.color.deltaE
    - luxpy.color.utils
    - luxpy.color.whiteness
    - luxpy.math
    - luxpy.math.DEMO
    - luxpy.math.vec3
    - luxpy.phot
    - luxpy.spectrum
    - luxpy.spectrum.basics
    - luxpy.utils

about:
  home: "https://github.com/ksmet1977/luxpy"
  license: GPLv3
  license_family: GPL3
  license_file: 
  summary: "Python package for lighting and color science"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
