{% set name = "luxpy" %}
{% set version = "1.4.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d2fc55e870e5dc9fa4c1f63b1dab2f87c1406bf4adfefabbb0f098b1aa99b4e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - imageio
    - matplotlib
    - numpy
    - pandas
    - pip
    - python
    - scipy
  run:
    - imageio
    - matplotlib
    - numpy
    - pandas
    - python
    - scipy

test:
  imports:
    - luxpy
    - luxpy.classes
    - luxpy.color
    - luxpy.color.cam
    - luxpy.color.cat
    - luxpy.color.cct
    - luxpy.color.cri
    - luxpy.color.cri.VFPX
    - luxpy.color.cri.iestm30
    - luxpy.color.cri.indices
    - luxpy.color.cri.utils
    - luxpy.color.ctf
    - luxpy.color.deltaE
    - luxpy.color.utils
    - luxpy.color.whiteness
    - luxpy.spectrum
    - luxpy.spectrum.basics
    - luxpy.utils
    - luxpy.utils.helpers
    - luxpy.utils.math
    - luxpy.utils.math.DEMO
    - luxpy.utils.math.vec3

about:
  home: https://github.com/ksmet1977/luxpy
  license: GPLv3
  license_family: GPL3
  license_file: 
  summary: Python package for lighting and color science
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
