{% set name = "luxpy" %}
{% set version = "1.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ab295325988cfaad3c10df4ed016ad87cd82b6cbcdd0053361ea21fb6f64a36d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - imageio
    - matplotlib
    - numpy
    - pandas
    - pip
    - python
    - scipy
  run:
    - imageio
    - matplotlib
    - numpy
    - pandas
    - python
    - scipy

test:
  imports:
    - luxpy
    - luxpy.color
    - luxpy.color.cam
    - luxpy.color.cat
    - luxpy.color.cct
    - luxpy.color.cri
    - luxpy.color.cri.VFPX
    - luxpy.color.cri.iestm30
    - luxpy.color.cri.indices
    - luxpy.color.cri.utils
    - luxpy.color.ctf
    - luxpy.color.deltaE
    - luxpy.color.utils
    - luxpy.color.whiteness
    - luxpy.math
    - luxpy.math.DEMO
    - luxpy.math.vec3
    - luxpy.spectrum
    - luxpy.spectrum.basics
    - luxpy.utils

about:
  home: "https://github.com/ksmet1977/luxpy"
  license: GPLv3
  license_family: GPL3
  license_file: 
  summary: "Python package for lighting and color science"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
